### ISSUE TITLE
aks-periscope do not deploy Pods for Windows Nodes

### ISSUE THREAD

**Issue by OvidiuBorlean** [Azure/aks-periscope#180] opened 2022-06-09 09:10 UTC
Hello,

We are trying to collect logs from our Windows Nodes in AKS Cluster. We deployed aks-periscope from Azure Cloud-Shell but it worked only for Linux nodes, as in our Storage found only those folders. Although there was a DaemonSet for Windows Nodes, no Pods has been started for this one. Could you please let me know how we should troubleshoot those issues? 
Will mention that we are using AKS Cluster integrated with AAD.
If need any logs from resources, we can provide as requested. 

Thank you

**Comment by Tatsinnit** [comment] 2022-06-09 23:00
Thank you so much @OvidiuBorlean for reporting this, can you please share how you are trying to deploy the tool? or replication steps for this issue please? I tried for a windows node and it worked so I thought I will ask. The windows image reference is: `mcr.microsoft.com/aks/periscope-win:0.0.9` Thanks ☕️ 🙏 cc: @peterbom as fyi.

**Comment by peterbom** [comment] 2022-06-09 23:25
Hi @OvidiuBorlean - were you using the `az aks kollect` command to deploy Periscope? There were some changes made to the CLI tool to support the latest Periscope version, and I'm guessing those haven't been released yet. I'll have to do more research to understand how/when the `aks-preview` extension gets released... @Tatsinnit - do you know anything about this?

In the meantime, you can try using the [VS Code AKS extension](https://code.visualstudio.com/docs/azure/aksextensions) to deploy Periscope. We have released that with the changes to support the latest Periscope release.

**Comment by peterbom** [comment] 2022-06-10 02:13
As for troubleshooting, the following commands might be helpful:
```sh
# Check the desired/ready/available pods for the DaemonSets (there should be two)
kubectl get ds -n aks-periscope

# Get more detail about the Windows DaemonSet
kubectl describe ds -n aks-periscope aks-periscope-win

# Check the statuses of all the Periscope pods
kubectl get po -n aks-periscope

# In case a pod is stuck in Pending (or some other not ready state), check the events at the bottom of:
kubectl describe po -n aks-periscope <podname>
```

**Comment by OvidiuBorlean** [comment] 2022-06-10 11:04
Hi everyone,

Thank you very much for your fast reply on this thread. This actually happened for one of our customer when tried to collect the Windows logs for troubleshooting process. I have done a repro on a AKS test cluster with AAD integration and it works just fine, with both admin user configured for cluster access and AAD user. Will try to get some more logs during the deployment for the affected cluster, maybe there is some particular configuration that is doing this. Thank you for your support

**Comment by Tatsinnit** [comment] 2022-06-10 14:11
Thanks you @OvidiuBorlean , glad it helped! Since it’s is working will it be cool if I close this issue, as no further action is in need? Kind regards!

**Comment by philshur** [comment] 2022-06-10 15:51
Thanks all, @peterbom Here are the responses from the commands you suggested after running aks collect from cloud shell bash terminal:

# Check the desired/ready/available pods for the DaemonSets (there should be two)
kubectl get ds -n aks-periscope

NAME                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR              AGE
aks-periscope       2         2         2       2            2           kubernetes.io/os=linux     19m
aks-periscope-win   0         0         0       0            0           kubernetes.io/os=windows   19m

# Get more detail about the Windows DaemonSet
kubectl describe ds -n aks-periscope aks-periscope-win

Name:           aks-periscope-win
Selector:       app=aks-periscope
Node-Selector:  kubernetes.io/os=windows
Labels:         app=aks-periscope
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app=aks-periscope
  Service Account:  aks-periscope-service-account
  Containers:
   aks-periscope:
    Image:      mcr.microsoft.com/aks/periscope-win:0.0.9
    Port:       <none>
    Host Port:  <none>
    Limits:
      cpu:     1
      memory:  2000Mi
    Requests:
      cpu:     250m
      memory:  500Mi
    Environment Variables from:
      diagnostic-config  ConfigMap  Optional: false
      azureblob-secret   Secret     Optional: false
    Environment:
      HOST_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /AzureData from azuredata (rw)
      /k from k (rw)
  Volumes:
   k:
    Type:          HostPath (bare host directory volume)
    Path:          /k
    HostPathType:  
   azuredata:
    Type:          HostPath (bare host directory volume)
    Path:          /AzureData
    HostPathType:  
Events:            <none>


# Check the statuses of all the Periscope pods
kubectl get po -n aks-periscope

NAME                  READY   STATUS    RESTARTS   AGE
aks-periscope-cqxqx   1/1     Running   0          20m
aks-periscope-fz2rh   1/1     Running   0          20m

# In case a pod is stuck in Pending (or some other not ready state), check the events at the bottom of:
kubectl describe po -n aks-periscope <podname>

N/A

**Comment by peterbom** [comment] 2022-06-11 01:00
Thanks for the extra info, @philshur and @OvidiuBorlean!

Given that the 'desired' pod count is 0, that suggests your cluster doesn't think it has any Windows nodes. Or at least there aren't any matching the selector `kubernetes.io/os=windows` that Kubernetes *thinks* it should schedule pods to.

Next things I can think of to look at:
```sh
# Check the AKS node pools (there should be one or more with `OsType` == `Windows`). Do they have `ProvisioningState` == `Succeeded`?
az aks nodepool list -g <resource_group> --cluster-name <aks_cluster> -o table

# Check the nodes - do any of them start with `aks<windows_node_pool_name>`?
kubectl get no

# If there are nodes in a Windows node pool which are successfully provisioned, check they all match the `selector` value:
kubectl get no --selector kubernetes.io/os=windows

# If there are still nodes that match that selector, I have no idea why they wouldn't be getting any pods! But if that's the case, we might get *some* insight from:
kubectl describe no <windows_node>
```

**Comment by philshur** [comment] 2022-06-13 09:58
Thanks @peterbom 

These are the responses I get from the above:

# Check the AKS node pools (there should be one or more with `OsType` == `Windows`). Do they have `ProvisioningState` == `Succeeded`?
az aks nodepool list -g <resource_group> --cluster-name <aks_cluster> -o table

Name       OsType    VmSize           Count    MaxPods    ProvisioningState    Mode
---------  --------  ---------------  -------  ---------  -------------------  ------
nodepool1  Linux     Standard_D4s_v4  2        250        Succeeded            System
winle      Windows   Standard_E8s_v5  0        250        Succeeded            User
winse      Windows   Standard_E4s_v5  1        250        Succeeded            User

# Check the nodes - do any of them start with `aks<windows_node_pool_name>`?
kubectl get no

NAME                                STATUS   ROLES   AGE   VERSION
aks-nodepool1-19583413-vmss000000   Ready    agent   11d   v1.21.7
aks-nodepool1-19583413-vmss000001   Ready    agent   11d   v1.21.7
akswinse000000                      Ready    agent   11d   v1.21.7

# If there are nodes in a Windows node pool which are successfully provisioned, check they all match the `selector` value:
kubectl get no --selector kubernetes.io/os=windows

NAME             STATUS   ROLES   AGE   VERSION
akswinse000000   Ready    agent   11d   v1.21.7

# If there are still nodes that match that selector, I have no idea why they wouldn't be getting any pods! But if that's the case, we might get *some* insight from:
kubectl describe no <windows_node>

Name:               akswinse000000
Roles:              agent
Labels:             agentpool=winse
                    beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=Standard_E4s_v5
                    beta.kubernetes.io/os=windows
                    failure-domain.beta.kubernetes.io/region=westus
                    failure-domain.beta.kubernetes.io/zone=0
                    kubernetes.azure.com/agentpool=winse
                    kubernetes.azure.com/cluster=MC_Kube-Experimental_starling-westus-experimental_westus
                    kubernetes.azure.com/kubelet-identity-client-id=
                    kubernetes.azure.com/mode=user
                    kubernetes.azure.com/node-image-version=AKSWindows-2019-17763.2803.220428
                    kubernetes.azure.com/role=agent
                    kubernetes.azure.com/storageprofile=managed
                    kubernetes.azure.com/storagetier=Premium_LRS
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=akswinse000000
                    kubernetes.io/os=windows
                    kubernetes.io/role=agent
                    node-role.kubernetes.io/agent=
                    node.kubernetes.io/instance-type=Standard_E4s_v5
                    node.kubernetes.io/windows-build=10.0.17763
                    storageprofile=managed
                    storagetier=Premium_LRS
                    topology.disk.csi.azure.com/zone=
                    topology.kubernetes.io/region=westus
                    topology.kubernetes.io/zone=0
Annotations:        csi.volume.kubernetes.io/nodeid: {"disk.csi.azure.com":"akswinse000000","file.csi.azure.com":"akswinse000000"}
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Wed, 01 Jun 2022 15:35:39 +0100
Taints:             node.kubernetes.io/os=windows:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  akswinse000000
  AcquireTime:     <unset>
  RenewTime:       Mon, 13 Jun 2022 10:07:41 +0100
Conditions:
  Type             Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----             ------  -----------------                 ------------------                ------                       -------
  MemoryPressure   False   Mon, 13 Jun 2022 10:06:17 +0100   Tue, 07 Jun 2022 22:49:13 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure     False   Mon, 13 Jun 2022 10:06:17 +0100   Tue, 07 Jun 2022 22:49:13 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure      False   Mon, 13 Jun 2022 10:06:17 +0100   Tue, 07 Jun 2022 22:49:13 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready            True    Mon, 13 Jun 2022 10:06:17 +0100   Tue, 07 Jun 2022 22:49:13 +0100   KubeletReady                 kubelet is posting ready status
Addresses:
  Hostname:    akswinse000000
  InternalIP:  10.224.1.250
Capacity:
  attachable-volumes-azure-disk:  16
  cpu:                            4
  ephemeral-storage:              267921404Ki
  memory:                         33553972Ki
  pods:                           250
Allocatable:
  attachable-volumes-azure-disk:  16
  cpu:                            3860m
  ephemeral-storage:              267921404Ki
  memory:                         27724340Ki
  pods:                           250
System Info:
  Machine ID:                 akswinse000000
  System UUID:                16CCB378-693C-452D-B32E-C183430EB4AC
  Boot ID:
  Kernel Version:             10.0.17763.2803
  OS Image:                   Windows Server 2019 Datacenter
  Operating System:           windows
  Architecture:               amd64
  Container Runtime Version:  docker://20.10.9
  Kubelet Version:            v1.21.7
  Kube-Proxy Version:         v1.21.7
ProviderID:                   azure:///subscriptions/cf9fa274-ff0f-4ec4-be0b-4f6fea78a018/resourceGroups/mc_kube-experimental_starling-westus-experimental_westus/providers/Microsoft.Compute/virtualMachineScaleSets/akswinse/virtualMachines/0
Non-terminated Pods:          (3 in total)
  Namespace                   Name                            CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                            ------------  ----------  ---------------  -------------  ---
  kube-system                 csi-azuredisk-node-win-wmv8c    30m (0%)      0 (0%)      60Mi (0%)        800Mi (2%)     11d
  kube-system                 csi-azurefile-node-win-b6fr9    30m (0%)      0 (0%)      60Mi (0%)        800Mi (2%)     3d21h
  kube-system                 omsagent-win-zdcfs              500m (12%)    500m (12%)  600Mi (2%)       600Mi (2%)     3d21h
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests    Limits
  --------                       --------    ------
  cpu                            560m (14%)  500m (12%)
  memory                         720Mi (2%)  2200Mi (8%)
  ephemeral-storage              0 (0%)      0 (0%)
  attachable-volumes-azure-disk  0           0
Events:                          <none>

**Comment by peterbom** [comment] 2022-06-13 21:55
@philshur - thank you for the extra info.

I _think_ the issue is in the output from `kubectl describe no`, specifically this:
```
Taints: node.kubernetes.io/os=windows:NoSchedule
```

According to the [kubernetes docs](https://kubernetes.io/docs/concepts/windows/user-guide/#ensuring-os-specific-workloads-land-on-the-appropriate-container-host), no pods will be scheduled to the node, unless they have a corresponding `toleration`, which the Periscope pods don't have.

The question now is what to do about it. I assume the taint is there for a reason, and you can't simply remove it?

I'm not sure if our Periscope deployment _should_ be specifying that toleration, and whether there would be any unintended consequences if we always did that. @Tatsinnit - we can discuss this and maybe create an issue?

In the meantime, it is possible to deploy Periscope manually by creating a `kustomization.yaml` file which I think we could use to set that toleration and see if we can get it to work that way. I'll have a try myself and post something here shortly.

**Comment by peterbom** [comment] 2022-06-13 22:55
@philshur - this works for me (with the taint applied to my Windows node):
```sh
# Set some variables for where you want the logs uploaded to:
sub_id=<storage_account_subscription_id>
stg_account=<storage_account_name>
blob_container=<desired_blob_container_name>

# Create a SAS for the storage account
sas_expiry=`date -u -d "60 minutes" '+%Y-%m-%dT%H:%MZ'`
sas=$(az storage account generate-sas \
    --account-name $stg_account \
    --subscription $sub_id \
    --permissions rwdlacup \
    --services b \
    --resource-types sco \
    --expiry $sas_expiry \
    -o tsv)

# Create a 'kustomization' folder to contain the Periscope resources to be deployed
mkdir ./periscope-deploy

# Create a YAML file to override the default deployment behaviour
cat <<EOF > ./periscope-deploy/kustomization.yaml
resources:
- https://github.com/azure/aks-periscope//deployment/base?ref=v0.9

patches:
- target:
    group: apps
    kind: DaemonSet
    name: aks-periscope-win
    version: v1
  patch: |-
    - op: add
      path: '/spec/template/spec/tolerations'
      value:
      - key: node.kubernetes.io/os
        operator: Equal
        value: windows
        effect: NoSchedule

images:
- name: periscope-linux
  newName: mcr.microsoft.com/aks/periscope
  newTag: "0.0.9"
- name: periscope-windows
  newName: mcr.microsoft.com/aks/periscope-win
  newTag: "0.0.9"

secretGenerator:
- name: azureblob-secret
  behavior: replace
  literals:
  - AZURE_BLOB_ACCOUNT_NAME=${stg_account}
  - AZURE_BLOB_SAS_KEY=?${sas}
  - AZURE_BLOB_CONTAINER_NAME=${blob_container}
EOF

# Deploy
kubectl apply -k ./periscope-deploy
```

After deploying, you _should_ be able to see a pod for the Windows node by running `kubectl get po -n aks-periscope`. Assuming that runs, the data collected by Periscope should be available in the Azure Portal, by navigating to the storage account and blob container specified in the variables above.

If you do try this, let me know how you get on!

**Comment by philshur** [comment] 2022-06-14 09:55
@peterbom thanks for your advice and quick responses!

That worked for me too, thanks again!

**Comment by peterbom** [comment] 2022-06-16 03:15
> I'm not sure if our Periscope deployment should be specifying that toleration, and whether there would be any unintended consequences if we always did that.

I've started a discussion (#183) about this, and made a few initial notes that lean towards _not_ changing our deployment. However, I have very little real-world Kubernetes experience, and would welcome any thoughts/corrections from folks in the field (@philshur, @OvidiuBorlean).

**Comment by Tatsinnit** [comment] 2022-06-20 00:51
Nice, thank you so much @peterbom for creating the discussion here (https://github.com/Azure/aks-periscope/discussions/183) for any further improvements. Given the primary issue is resolved I will close this issue and move rest of ideas and discussion to discussion board. Thank you so much to @philshur, @OvidiuBorlean for reporting this and we have clarity in unblocking this for any other user if need be.

**Closed by Tatsinnit** 2022-06-20 00:51 UTC
Labels: question 🙋
